[package]
name = "sniffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.9.2"
pnet = "0.31.0"
rayon = "1.5.3"
chrono = "0.4.22"
crossterm = "0.25.0"
prettytable-rs = "^0.9"